/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlaylistsRouteImport } from './routes/playlists'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as DispositivosRouteImport } from './routes/dispositivos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as BaixarApkRouteImport } from './routes/baixar-apk'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaylistsIdRouteImport } from './routes/playlists.$id'
import { Route as PlaylistsIdPreviewRouteImport } from './routes/playlists.$id.preview'
import { Route as ApiPublicApkRouteImport } from './routes/api/public/apk'

const PlaylistsRoute = PlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const DispositivosRoute = DispositivosRouteImport.update({
  id: '/dispositivos',
  path: '/dispositivos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const BaixarApkRoute = BaixarApkRouteImport.update({
  id: '/baixar-apk',
  path: '/baixar-apk',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIdRoute = PlaylistsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PlaylistsRoute,
} as any)
const PlaylistsIdPreviewRoute = PlaylistsIdPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => PlaylistsIdRoute,
} as any)
const ApiPublicApkRoute = ApiPublicApkRouteImport.update({
  id: '/api/public/apk',
  path: '/api/public/apk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/baixar-apk': typeof BaixarApkRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dispositivos': typeof DispositivosRoute
  '/player': typeof PlayerRoute
  '/playlists': typeof PlaylistsRouteWithChildren
  '/playlists/$id': typeof PlaylistsIdRouteWithChildren
  '/api/public/apk': typeof ApiPublicApkRoute
  '/playlists/$id/preview': typeof PlaylistsIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/baixar-apk': typeof BaixarApkRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dispositivos': typeof DispositivosRoute
  '/player': typeof PlayerRoute
  '/playlists': typeof PlaylistsRouteWithChildren
  '/playlists/$id': typeof PlaylistsIdRouteWithChildren
  '/api/public/apk': typeof ApiPublicApkRoute
  '/playlists/$id/preview': typeof PlaylistsIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/baixar-apk': typeof BaixarApkRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/dispositivos': typeof DispositivosRoute
  '/player': typeof PlayerRoute
  '/playlists': typeof PlaylistsRouteWithChildren
  '/playlists/$id': typeof PlaylistsIdRouteWithChildren
  '/api/public/apk': typeof ApiPublicApkRoute
  '/playlists/$id/preview': typeof PlaylistsIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/baixar-apk'
    | '/clientes'
    | '/configuracoes'
    | '/dispositivos'
    | '/player'
    | '/playlists'
    | '/playlists/$id'
    | '/api/public/apk'
    | '/playlists/$id/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/baixar-apk'
    | '/clientes'
    | '/configuracoes'
    | '/dispositivos'
    | '/player'
    | '/playlists'
    | '/playlists/$id'
    | '/api/public/apk'
    | '/playlists/$id/preview'
  id:
    | '__root__'
    | '/'
    | '/baixar-apk'
    | '/clientes'
    | '/configuracoes'
    | '/dispositivos'
    | '/player'
    | '/playlists'
    | '/playlists/$id'
    | '/api/public/apk'
    | '/playlists/$id/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaixarApkRoute: typeof BaixarApkRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  DispositivosRoute: typeof DispositivosRoute
  PlayerRoute: typeof PlayerRoute
  PlaylistsRoute: typeof PlaylistsRouteWithChildren
  ApiPublicApkRoute: typeof ApiPublicApkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispositivos': {
      id: '/dispositivos'
      path: '/dispositivos'
      fullPath: '/dispositivos'
      preLoaderRoute: typeof DispositivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baixar-apk': {
      id: '/baixar-apk'
      path: '/baixar-apk'
      fullPath: '/baixar-apk'
      preLoaderRoute: typeof BaixarApkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$id': {
      id: '/playlists/$id'
      path: '/$id'
      fullPath: '/playlists/$id'
      preLoaderRoute: typeof PlaylistsIdRouteImport
      parentRoute: typeof PlaylistsRoute
    }
    '/playlists/$id/preview': {
      id: '/playlists/$id/preview'
      path: '/preview'
      fullPath: '/playlists/$id/preview'
      preLoaderRoute: typeof PlaylistsIdPreviewRouteImport
      parentRoute: typeof PlaylistsIdRoute
    }
    '/api/public/apk': {
      id: '/api/public/apk'
      path: '/api/public/apk'
      fullPath: '/api/public/apk'
      preLoaderRoute: typeof ApiPublicApkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlaylistsIdRouteChildren {
  PlaylistsIdPreviewRoute: typeof PlaylistsIdPreviewRoute
}

const PlaylistsIdRouteChildren: PlaylistsIdRouteChildren = {
  PlaylistsIdPreviewRoute: PlaylistsIdPreviewRoute,
}

const PlaylistsIdRouteWithChildren = PlaylistsIdRoute._addFileChildren(
  PlaylistsIdRouteChildren,
)

interface PlaylistsRouteChildren {
  PlaylistsIdRoute: typeof PlaylistsIdRouteWithChildren
}

const PlaylistsRouteChildren: PlaylistsRouteChildren = {
  PlaylistsIdRoute: PlaylistsIdRouteWithChildren,
}

const PlaylistsRouteWithChildren = PlaylistsRoute._addFileChildren(
  PlaylistsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaixarApkRoute: BaixarApkRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  DispositivosRoute: DispositivosRoute,
  PlayerRoute: PlayerRoute,
  PlaylistsRoute: PlaylistsRouteWithChildren,
  ApiPublicApkRoute: ApiPublicApkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
